"""add weight to animals

Revision ID: 7fbd17e6f4d9
Revises: 0308aee43fc6
Create Date: 2026-09-17 11:19:48.133438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbd17e6f4d9'
down_revision: Union[str, Sequence[str], None] = '0308aee43fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'weight')
    # ### end Alembic commands ###
